---
bins:
  show: true
  input_info:
    input_type: sliderInput
    input_params:
      inputId: bins
      label: Bins
      min: 0
      max: 50
      value: 10
      step: 1
  update_param: value
dataset:
  show: true
  input_info:
    input_type: selectInput
    input_params:
      inputId: dataset
      label: Dataset
      choices:
        - rock
        - pressure
        - cars
      selected: rock
  update_param: selected
column:
  show: true
  input_info:
    input_type: numericInput
    input_params:
      inputId: column
      label: Column
      value: 1
  update_param: value
